<div class="container">
    <h3 class="display-3">Witaj w myWords!</h3>
    <h5>Jesteś w trybie przeglądania. Poniżej wyświetlamy Ci nowe słowo i jego tłumaczenie. Postaraj się je zapamiętać, w kolejnych trybach nauki sprawdzimy czy je znasz. Użyj przycisku "Następne słowo" aby wyświetlać nowe słowa. W każdej chwili możesz też zmienić kategorię słów lub przejść do kolejnego trybu nauki. Miłej zabawy!</h5>
</div>