<div class="container">
    <h3 class="display-3">Witaj w myWords!</h3>
    <h5>Jesteś w trybie nauki. W tym trybie wyświetlamy słowa, które już poznałeś.
        Kliknij w niebieski przycisk aby sprawdzić poprawne tłumaczenie słowa i ocenić, czy już je znasz.
        Od Twojej oceny zależy, czy słowo będzie nadal dostępne, czy przejdzie do trybu powtórek.
        W każdej chwili możesz też zmienić kategorię słów lub przejść do kolejnego trybu nauki. Miłej zabawy!</h5>
</div>