<div class="container">
    <h3 class="display-3">Witaj w myWords!</h3>
    <h5>Jesteś w trybie powtórek.
        Poniżej wyświetlamy Ci słowa, które powinieneś już znać.
        Kliknij w niebieski przycisk aby sprawdzić poprawne tłumaczenie słowa i ocenić,
        czy słowo ma być nadal wyświetlane w programie, czy może znasz je na tyle dobrze, że ma zostać usunięte.
        Miłej zabawy!</h5>
</div>