<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>

    <meta charset="utf-8">
    <title>error</title>
</head>
<body>
<main>
    <center></center><img src="/home/sebastianbieluga/projektaktualny01/jjdd4-emememsy/web/src/main/webapp/images" width="400" height= "500" /></center>




    <center><div><font size="24"> ups ... something went wrong</div></center></font>




</main>



</body>
</html>